# SPDX-License-Identifier: Apache-2.0
# Keep the upstream common vendor tree untouched. Nabu has no cellular modem,
# GNSS, FM, camera motor or payment/fingerprint hardware. Shared dependencies
# of retained HALs (including libqcbor and Bluetooth FM interfaces) and the
# QRTR/PD, remote storage and TFTP services used by DSP peripherals must remain
# installed even on an APQ tablet without cellular networking.
include vendor/xiaomi/sm8150-common/sm8150-common-vendor.mk

NABU_PHONE_ONLY_COPY_DESTINATIONS := \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib/com.qualcomm.qti.ant@1.0.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib/fm_helium.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib/libfm-hci.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib/vendor.qti.hardware.fm@1.0.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/com.qualcomm.qti.ant@1.0.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/fm_helium.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/lib-imsvideocodec.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/lib-imsvt.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/lib-imsvtextutils.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/lib-imsvtutils.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libfm-hci.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libimscamera_jni.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/libimsmedia_jni.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.hardware.fm@1.0.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.imsrtpservice@3.0.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/lib64/vendor.qti.imsrtpservice@3.1.so \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_cangmen_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_cangmen_up.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_chilun_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_chilun_up.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_jijia_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_jijia_up.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_mofa_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_mofa_up.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_muqin_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_muqin_up.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_yingyan_down.ogg \
    $(TARGET_COPY_OUT_SYSTEM_EXT)/media/audio/ui/popup_yingyan_up.ogg \
    $(TARGET_COPY_OUT_VENDOR)/bin/ATFWD-daemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/adpl \
    $(TARGET_COPY_OUT_VENDOR)/bin/fm_qsoc_patches \
    $(TARGET_COPY_OUT_VENDOR)/bin/hw/android.hardware.gnss@2.1-service-qti \
    $(TARGET_COPY_OUT_VENDOR)/bin/hw/qcrild \
    $(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.hardware.alarm@1.0-service \
    $(TARGET_COPY_OUT_VENDOR)/bin/hw/vendor.qti.hardware.soter@1.0-service \
    $(TARGET_COPY_OUT_VENDOR)/bin/ims_rtp_daemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/imsdatadaemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/imsqmidaemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/imsrcsd \
    $(TARGET_COPY_OUT_VENDOR)/bin/ks \
    $(TARGET_COPY_OUT_VENDOR)/bin/loc_launcher \
    $(TARGET_COPY_OUT_VENDOR)/bin/lowi-server \
    $(TARGET_COPY_OUT_VENDOR)/bin/mdm_helper \
    $(TARGET_COPY_OUT_VENDOR)/bin/mlid \
    $(TARGET_COPY_OUT_VENDOR)/bin/mlipayd@1.1 \
    $(TARGET_COPY_OUT_VENDOR)/bin/netmgrd \
    $(TARGET_COPY_OUT_VENDOR)/bin/port-bridge \
    $(TARGET_COPY_OUT_VENDOR)/bin/power_off_alarm \
    $(TARGET_COPY_OUT_VENDOR)/bin/qrtr-cfg \
    $(TARGET_COPY_OUT_VENDOR)/bin/qrtr-lookup \
    $(TARGET_COPY_OUT_VENDOR)/bin/qti \
    $(TARGET_COPY_OUT_VENDOR)/bin/slim_daemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/ssgqmigd \
    $(TARGET_COPY_OUT_VENDOR)/bin/ssgtzd \
    $(TARGET_COPY_OUT_VENDOR)/bin/xtra-daemon \
    $(TARGET_COPY_OUT_VENDOR)/bin/xtwifi-client \
    $(TARGET_COPY_OUT_VENDOR)/bin/xtwifi-inet-agent \
    $(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    $(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    $(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    $(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/init.qti.fm.sh \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.fm.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc \
    $(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    $(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/atfwd@2.0.policy \
    $(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    $(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    $(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    $(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    $(TARGET_COPY_OUT_VENDOR)/etc/xtwifi.conf \
    $(TARGET_COPY_OUT_VENDOR)/lib/hw/vendor.qti.hardware.fm@1.0-impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib/vendor.qti.hardware.fm@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.imscmservice@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.imscmservice@2.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.imscmservice@2.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.imscmservice@2.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.uceservice@2.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.uceservice@2.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/com.qualcomm.qti.uceservice@2.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/deviceInfoServiceModule.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/hw/android.hardware.gnss@2.1-impl-qti.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.gnss@4.0-impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.hardware.alarm@1.0-impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.hardware.fm@1.0-impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/hw/vendor.qti.hardware.soter@1.0-impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imscmservice.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsdpl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsqimf.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcs-v2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsrcsbaseimpl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsvtcore.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-imsxml.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-rcsconfig.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcommon.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpcore.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-rtpsl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-siputility.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/lib-uceservice.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libaoa.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libbatching.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libcacertclient.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libdataitems.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libgdtap.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libgeofencing.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libgnss.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libgnsspps.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libizat_client_api.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libizat_core.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libjnihelper.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblbs_core.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libloc_api_v02.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libloc_core.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libloc_socket.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblocation_api.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblocationservice_glue.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_client.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblowi_wifihal.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liblqe.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libmdmimgload.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libmlipay.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libmlipay@1.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr_common.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr_nr_fusion.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libnetmgr_rmnet_ext.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libnlnetmgr.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/liboemaids_vendor.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libpdmapper.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libpdnotifier.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libqcc_file_agent.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libqcrilFramework.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libqcrildatactl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libqdma_file_agent.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/librcc.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-hal-qmi.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-logger.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-ltedirectdisc.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libril-qc-radioconfig.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libril-qcril-hook-oem.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/librilqmiservices.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libsettings.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libslimclient.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libsystem_health_mon.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/libxtadapter.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/qcrild_librilutils.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/qtibus.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/qtimutex.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@1.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@1.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@2.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@2.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@3.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@4.0-service.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.gnss@4.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.alarm@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.am@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.atcmdfwd@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.3.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.4.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.5.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.ims@1.6.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.internal.deviceinfo@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.lpa@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qcrilhook@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@2.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@2.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@2.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@2.3.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.qtiradio@2.4.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim@1.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim@1.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.2.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.radio.uim_remote_server@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.hardware.soter@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.ims.callcapability@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.ims.callinfo@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.ims.factory@1.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.ims.rcsconfig@2.0.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.ims.rcsconfig@2.1.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.imsrtpservice@3.0-service-Impl.so \
    $(TARGET_COPY_OUT_VENDOR)/lib64/vendor.qti.imsrtpservice@3.0.so \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    $(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql

PRODUCT_COPY_FILES := $(foreach entry,$(PRODUCT_COPY_FILES),$(if $(filter $(word 2,$(subst :, ,$(entry))),$(NABU_PHONE_ONLY_COPY_DESTINATIONS)),,$(entry)))
PRODUCT_PACKAGES := $(filter-out IWlanService PowerOffAlarm QtiTelephonyService android.hardware.gnss@2.1-service-qti ims manifest_vendor.xiaomi.hardware.mlipay qcrilhook qcrilmsgtunnel vendor.qti.gnss@4.0-service vendor.qti.hardware.alarm-V1.0-java,$(PRODUCT_PACKAGES))
